SYSTEM: matgen-dos
ISYM: 2
ISTART: 1
ISPIN: 2
ICHARG: 11
LREAL: Auto
ENCUT: 520
PREC: Accurate
LWAVE: .F.
LCHARG: .F.
ADDGRID: .T.
NPAR: 4
NBLOCK: 1
INIWAV: 1
ISMEAR: 0 
SIGMA: 0.05
ALGO: Normal
NELM: 200
NELMIN: 6
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 2
EDIFFG: -1E-02
POTIM: 0.2
LORBIT: 11
NEDOS: 2001
AMIX: 0.1
BMIX: 1.2
WEIMIN: 0
