SYSTEM: matgen-relax
ISTART: 0
ISYM: 2
ISPIN: 2
LREAL: Auto
ENCUT: 520
PREC: Accurate
LWAVE: .F.
LCHARG: .F.
ADDGRID: .T.
NPAR: 4
NBLOCK: 1
INIWAV: 1
ISMEAR: 0 
SIGMA: 0.05
ALGO: Normal
NELM: 60
NELMIN: 6
EDIFF: 1E-04
NSW: 40
IBRION: 2
ISIF: 3
EDIFFG: -1E-03
POTIM: 0.05
LCORR: .T.
AMIX: 0.1
BMIX: 1.2
